# Generated by Django 4.2.15 on 2024-09-06 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_productset'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizeGuid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=20)),
                ('labels', models.TextField()),
                ('values', models.TextField()),
                ('is_available', models.BooleanField(default=True)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='main.product')),
            ],
        ),
    ]
