# Generated by Django 4.2.15 on 2024-09-07 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_size', to='main.sizeguid'),
        ),
    ]
