# Generated by Django 4.2.15 on 2024-09-07 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_cart_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='products',
            new_name='product',
        ),
    ]
