# Generated by Django 4.2.15 on 2024-09-10 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_order_shipping_payment_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
        migrations.RemoveField(
            model_name='shipping',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_detail',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='main.payment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='main.shipping'),
            preserve_default=False,
        ),
    ]
