# Generated by Django 4.2.15 on 2024-09-11 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_payment_order_remove_shipping_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='amount',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
    ]
