# Generated by Django 4.2.15 on 2024-09-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_rename_amount_cart_quantity_remove_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='state',
            field=models.CharField(default='Abuja', max_length=100),
            preserve_default=False,
        ),
    ]
