# Generated by Django 4.2.15 on 2024-09-17 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_payment_amount_payment_tx_ref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available_size',
        ),
    ]
