# Generated by Django 4.2.15 on 2024-09-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_product_available_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payload',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
