# Generated by Django 4.2.15 on 2024-09-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_payment_payload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payload',
            field=models.TextField(blank=True, null=True),
        ),
    ]
