# Generated by Django 4.2.15 on 2024-09-20 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_payment_payload'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
