# Generated by Django 4.2.15 on 2024-09-22 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_orderitem_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipping',
            old_name='state',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='shipping',
            name='email',
            field=models.EmailField(default='tes@gmai.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipping',
            name='last_name',
            field=models.CharField(default='ismail', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipping',
            name='phone',
            field=models.CharField(default='obansa', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer')], default='credit_card', max_length=50),
        ),
    ]
