# Generated by Django 4.2.15 on 2024-09-26 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_rename_state_shipping_first_name_shipping_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('delivery_time', models.CharField(max_length=100)),
                ('flat_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('free_shipping_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('base_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('state_multiplier', models.JSONField()),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.shippingmethod')),
            ],
            options={
                'ordering': ['country', 'state'],
            },
        ),
    ]
