# Generated by Django 4.2.15 on 2024-09-27 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_shippingmethod_shippingrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingrate',
            name='state_multiplier',
            field=models.JSONField(null=True),
        ),
    ]
