# Generated by Django 4.2.15 on 2024-09-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_shippingrate_state_multiplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingrate',
            name='state_multiplier',
            field=models.JSONField(default=dict),
        ),
    ]
