# Generated by Django 4.2.15 on 2024-10-01 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_shippingrate_state_multiplier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingmethod',
            old_name='flat_rate',
            new_name='rate_multiplier',
        ),
        migrations.RemoveField(
            model_name='shippingrate',
            name='method',
        ),
        migrations.AddField(
            model_name='shippingmethod',
            name='country_exceptions',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
