# Generated by Django 4.2.15 on 2024-10-01 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_rename_flat_rate_shippingmethod_rate_multiplier_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingrate',
            options={'ordering': ['country']},
        ),
        migrations.RemoveField(
            model_name='shippingrate',
            name='state',
        ),
    ]
