# Generated by Django 4.2.15 on 2024-10-01 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_shippingrate_options_remove_shippingrate_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='order', to='main.shippingmethod'),
            preserve_default=False,
        ),
    ]
