# Generated by Django 4.2.15 on 2024-10-01 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_order_shipping_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='state',
            field=models.CharField(default='Abuja', max_length=100),
            preserve_default=False,
        ),
    ]
