# Generated by Django 4.2.15 on 2024-10-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_shipping_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.JSONField(),
        ),
    ]
