# Generated by Django 4.2.15 on 2024-10-04 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_alter_orderitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingmethod',
            name='country_exceptions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='shippingmethod',
            name='free_shipping_threshold',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
