# Generated by Django 4.2.15 on 2024-10-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_alter_shippingmethod_country_exceptions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ng_price',
            field=models.IntegerField(default=0),
        ),
    ]
