# Generated by Django 4.2.15 on 2024-10-07 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_product_ng_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(default='ngn', max_length=3),
        ),
    ]
