# Generated by Django 4.2.15 on 2024-10-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_order_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingmethod',
            name='rate_multiplier',
            field=models.FloatField(),
        ),
    ]
