# Generated by Django 4.2.15 on 2024-12-11 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_remove_user_country_alter_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(default='Nigeria', max_length=100),
            preserve_default=False,
        ),
    ]
