name: Deploy Backend to Vercel

on:
  push:
    branches: [ "backend" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy Backend
        run: vercel deploy --prod --yes --token=${{ secrets.VERCEL_TOKEN }} --name=thisowned-server
